name: Send Daily News Email

on:
  schedule:
    - cron: '0 8 * * *'   # 每天台灣時間下午4點
  workflow_dispatch:

jobs:
  send-email:
    runs-on: ubuntu-latest

    env:
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      NEWS_RECIPIENT: ${{ secrets.NEWS_RECIPIENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run script
        run: python rss_top_titles.py
